//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admitdetail
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Name { get; set; }
        public string Doctor_s_Name { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public string BedNo { get; set; }
    }
}
