//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admitdetail
    {
        public int ID { get; set; }
        public Nullable<int> PatientId { get; set; }

        [Required(ErrorMessage ="Name is required")]
        [DisplayName("Patient Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = " Name is required")]
        [DisplayName("Doctor's Name")]
        public string Doctor_sName { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }

        [Required(ErrorMessage = "Roon No is required")]
        
        public Nullable<int> RoomNo { get; set; }

        [Required(ErrorMessage = "Bed No is required")]
        public Nullable<int> BedNo { get; set; }
    }
}
