//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admitdetail
    {
        public int Id { get; set; }

        [Required(ErrorMessage = " please enter the patientId")]
        [DisplayName("PatientId ")]
        public Nullable<int> PatientId { get; set; }

        [Required(ErrorMessage = "please enter the Name")]
        [DisplayName("Name")]
        public string Name { get; set; }
        public string Doctor_s_Name { get; set; }


        [Required(ErrorMessage = "please enter the CheckIn")]
        [DisplayName("CheckIn")]
        public Nullable<System.DateTime> CheckIn { get; set; }


        [Required(ErrorMessage = "please enter the RoomNo")]
        [DisplayName("RoomNo")]
        public Nullable<int> RoomNo { get; set; }
        public string BedNo { get; set; }
    }
}
