//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_demo
    {
        public int C_Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Mobile { get; set; }
        public string Payment_type { get; set; }
        public string Doctor_s_Name { get; set; }
        public string Desgination { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Consulation { get; set; }
        public Nullable<decimal> Regulation { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    }
}
