//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="select anyone ")]
        public string speciality { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Name is required ")]

        public string LastName { get; set; }
        public string Gender { get; set; }

        [DisplayName("Date of Birth")]
        public Nullable<System.DateTime> Date_of_Birth { get; set; }

        [Required(ErrorMessage = "Mobile Number is required ")]
        [DisplayName("Phone Number")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Email is required ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Designation is required ")]
        public string Designation { get; set; }

        [Required(ErrorMessage = "Department is required ")]
        public string Department { get; set; }
        [DisplayName("Date of Joining")]
        public Nullable<System.DateTime> Date_of_joining { get; set; }

        [Required(ErrorMessage = "Address is required ")]
        public string Address { get; set; }

        [Required(ErrorMessage = "City is required ")]
        public string City { get; set; }

        [Required(ErrorMessage = "State is required ")]

        public string State { get; set; }
    }
}
